sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t navdeep1979/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true navdeep1979/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-us-east-1-748746311968"
  bucket_path: "Docker1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
